# Generated by Django 5.0.7 on 2024-08-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
