# Generated by Django 5.0.7 on 2024-08-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todolist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
