# Generated by Django 5.0.7 on 2024-08-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todolist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='user_id',
        ),
    ]
