# Generated by Django 5.0.7 on 2024-08-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_rename_user_id_todolist_user'),
    ]

    operations = [
    ]
