# Generated by Django 5.0.7 on 2024-08-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_auto_20240805_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user',
            new_name='user_id',
        ),
    ]
