# Generated by Django 5.0.7 on 2024-08-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_rename_user_todolist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
    ]
